---
- name: Install Fish (Debian).
  ansible.builtin.apt:
    name:
      - fish
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Change the default shell
  ansible.builtin.shell: chsh -s $(which fish)

